### ISSUE TITLE
Sources Integration with FE and vector tiles and db

### ISSUE THREAD

**Issue by zoobot** [waterthetrees/.github#1]
- [x] Users will be able to view and Add new sources from front end 
    waterthetrees/wtt_front#282
    https://github.com/waterthetrees/wtt_front/pull/401
    
- [x] API work to add new sources from front end to the sources table in the DB
   https://github.com/waterthetrees/wtt_db/pull/50
   https://github.com/waterthetrees/wtt_server/pull/126

- [ ] Update Cities and Countries when new source added
https://github.com/waterthetrees/wtt_server/issues/137

- [ ] Create an organization table in db and update organization and user when new source added
   
- [ ] All current trees will be saved in the sources table in the DB
   https://github.com/waterthetrees/wtt_db/pull/48
   https://github.com/waterthetrees/tree-sources/pull/15

- [ ] Css fixes for FE sources
   https://github.com/waterthetrees/wtt_front/issues/580
