### ISSUE TITLE
[Epic] Notifications

### ISSUE THREAD

**Issue by zoobot** [waterthetrees/.github#2]
### Resources:
- Tagging Ticket [#285](https://github.com/waterthetrees/wtt_front/issues/285) as it is was the initial conversation for notifications
- Design Figma: https://www.figma.com/file/5C3v1LUNwMPQy9JOgnKEtr/Water-the-Trees?node-id=1355%3A9085

### Milestone 0 - Design / Planning - 

https://knak.com/blog/blog/7-ux-strategies-for-great-email-design/
https://www.wowmakers.com/blog/ux-design-for-email-marketing-guide/
https://blog.hubspot.com/blog/tabid/6307/bid/33987/11-types-of-marketing-emails-you-could-be-sending-free-templates.aspx

- [ ] [Notifications - Design] Survey Email regarding the app
- [ ] [Notifications - Design] Monthly update email regarding new features / updated features (Newsletter)
- [ ] [Notifications - Design] Get started email (when you open an account)
- [ ] [Notifications - Design] Event Invitation Emails
- [ ] [Notifications - Design] Organizations / Team Invitation Emails
- [ ] [Notifications - Design] Leaderboard Email
- [ ] [Notifications - Design] Accomplishments / Badge Email
- [ ] [Notifications - Design] Monthly user total maintenance performed email 
- [ ] [Notifications - Design] Invite friends Email
- [ ] [Notifications - Design] Treasure Hunt Email
- [ ] [Notifications - Design] Promote Stakeholders Email
- [ ] [Notifications - Design] Happy Birthday Email
- [ ] [Notifications - Design] WTT Yearly Anniversary Email
- [ ] [Notifications - Design] Upload Sources Email
- [ ] [Notifications - Design] Help Locate Water Sources for watering trees email
- [ ] [Notifications - Design] Donate Email
- [ ] [Notifications - Design] WTT participated in tree planting / maintenance email
- [ ] [Notifications - Design] Best Practices to Maintaining trees email
- [ ] [Notifications - Design] 

### Milestone 1 - We will need user notifications for a variety of events

- [ ] [Create notifications db table](https://github.com/waterthetrees/wtt_db/issues/52)
- [ ] [Design notification bubble for FE](https://github.com/waterthetrees/wtt_db/issues/52)
- [ ] [Watering notifications for weather events](https://github.com/waterthetrees/wtt_notifications/pull/11)
- [ ] https://github.com/waterthetrees/wtt_notifications/issues/8
